geldarnetwork/config/routes.rb
Rails.application.routes.draw do
  
  authenticate :user do
    resources :timelines,
      only: [:index, :show],
      param: :username
    resources :posts, only: [:create, :show, :destroy]
    resources :bonds, param: :username do
      member do
        post :follow
        post :unfollow
        post :accept
        post :reject
        get :followers
        get :following
      end
    end
    namespace :settings do
      resource :user, only: [:show, :update]
    end
    namespace :api do
      namespace :v1 do
        resources :places, only: [:index]
      end
    end
  end
  devise_for :users
  root to: 'home#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

geldarnetwork/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           not null
#  is_public              :boolean          default(TRUE), not null
#  last_name              :string
#  locale                 :string           default("en-US"), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extract_roles_from :role
  devise :database_authenticatable, 
    :registerable,
    :recoverable, 
    :rememberable, 
    :validatable, 
    authentication_keys: [:login],
    reset_password_keys: [:login]

  attr_writer :login
  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates :first_name, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address"}
  has_many :bonds, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_one_attached :profile_picture
  has_many :followings,
  -> { Bond.following },
  through: :bonds,
  source: :friend, 
  dependent: :destroy

  has_many :follow_requests,
  -> { Bond.requesting },
  through: :bonds,
  source: :friend, 
  dependent: :destroy

  has_many :inward_bonds,
  class_name: "Bond",
  foreign_key: :friend_id, 
  dependent: :destroy

  has_many :followers,
  -> { Bond.following },
  through: :inward_bonds,
  source: :user, 
  dependent: :destroy
  scope :following, -> { where(state: FOLLOWING)}
  scope :requesting, -> { where(state: REQUESTING)}
  scope :blocking, -> { where(state: BLOCKING)}
  before_save :ensure_proper_name_case
  
  def to_param
    username
  end
  def login
    @login || username || email
  end
  def role
    username == "alex" ? :admin : :member
  end
  def self.find_authenticatable(login)
      where("username = :value OR email = :value", value: login).first
  end
  def self.find_for_database_authentication(conditions)
      conditions = conditions.dup
      login = conditions.delete(:login).downcase
      find_authenticatable(login)
  end
  def self.send_reset_password_instructions(conditions)
    recoverable = find_recoverable_or_init_with_errors(conditions)

    if recoverable.persisted?
    recoverable.send_reset_password_instructions
    end
    recoverable
  end

  def self.find_recoverable_or_init_with_errors(conditions)
      conditions = conditions.dup
      login = conditions.delete(:login).downcase
      recoverable = find_authenticatable(login)

      unless recoverable
      recoverable = new(login: login)
      recoverable.errors.add(:login, login.present? ? :not_found : :blank)
      end
      recoverable
  end
  private
  def ensure_proper_name_case
      self.first_name = first_name.capitalize
  end
end

geldarnetwork/app/controllers/settings/users_controller.rb
class Settings::UsersController < ApplicationController
  def show
  end

  def update
    current_user.assign_attributes permitted_params
    changes = current_user.changes

    
      if current_user.save
        flash[:notice] = "Profile's settings updated"
      else 
        flash[:alert] = "Unablet to update the profile settings"
      end
    

    redirect_to settings_user_path
  end
  private

  def permitted_params
    params.require(:user).permit(
      :username,
      :first_name,
      :last_name,
      :is_public,
      :profile_picture,
    )
  end
end

geldarnetwork/app/helpers/settings/users_helper.rb
module Settings::UsersHelper
end

geldarnetwork/app/views/settings/users/show.html.erb
<div class="settings">
    <div class="setting-form">
        <%= form_with model: current_user,
        url: settings_user_path,
        method: :patch do |f| %>

        <div class="field">
            <%= f.label :profile_picture %>
            <%= image_tag user_profile_picture(current_user, 100) %>
            <%= f.file_field :profile_picture %>
        </div>

        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
        </div>

        <div class="field">
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
        </div>

        <div class="field">
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
        </div>
        
        <div class="field">
            <%= f.label :is_public, "Public account?" %>
            <div class="checkbox-unit">
                <%= f.check_box :is_public %>
                <span class="help-text">
                    Allow everyone, including those who don't follow me,
                    to discover my updates.
                </span>
            </div>
        </div>
        <div class="field">
            <p> <%= link_to "Unhappy? Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %></p>
        </div>
        <div>
            <%= f.submit "Update", class: "submit-btn" %>
        </div>
        <% end %>
    </div>
</div>

geldarnetwork/app/views/settings/users/update.html.erb
<h1>Settings::Users#update</h1>
<p>Find me in app/views/settings/users/update.html.erb</p>