geldarnetwork/config/routes.rb
Rails.application.routes.draw do
  
  authenticate :user do
    resources :timelines,
      only: [:index, :show],
      param: :username
    resources :posts, only: [:create, :show, :destroy]
    resources :bonds, param: :username do
      member do
        post :follow
        post :unfollow
        post :accept
        post :reject
        get :followers
        get :following
      end
    end
    namespace :settings do
      resource :user, only: [:show, :update]
    end
    namespace :api do
      namespace :v1 do
        resources :places, only: [:index]
      end
    end
  end
  devise_for :users
  root to: 'home#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

geldarnetwork/app/views/layouts/member/_navbar.html.erb
<nav class="topnav">
    <div class="flex item-center flex-shrink-0 mb-4 mt-2">
        <%= link_to timelines_path do %>
            <%= image_tag 'geldarnetwork-logo-gray-text-1000x350.svg', alt: 'Geldar Network' %> 
        <% end %>
        <%= language_selector %>
    </div>
    <div class="block flex-grow flex items-center w-auto">
        <div class="text-sm flex-grow">
            <%= link_to timelines_path, 
                class: "linked-icon #{"active" if on_bunch?}" do %>
                <%= evil_icon "ei-timeline" %>
            <% end %>
            <%= link_to timeline_path(current_user),
                class: "linked-icon #{"active" if on_self?}" do %>
                <%= evil_icon "ei-user" %>
            <% end %>
            <%= link_to settings_user_path, 
                class: "linked-icon #{"active" if on_settings?}" do %>
                <%= evil_icon "ei-gear" %>
            <% end %>
        </div>
        <div>
            <%= link_to destroy_user_session_path,
                class: "linked-icon sign-out",
                method: :delete do %>
                <%= evil_icon "ei-external-link" %>
            <% end %>
        </div>
    </div>
</nav>